version: '3.8'
services:
  backend:
    build: ./server
    ports:
      - "5000:5000"
    env_file: ./server/.env
  frontend:
    build: ./client
    restart: unless-stopped
    ports:
      - "5173:5173"
    stdin_open: true # Needed for Vite/React to stay alive